/**
 * @LAYOUT_HEADER_HEIGHT  顶部高度
 * @LAYOUT_SIDERBAR_WIDTH  侧边导航栏展开宽度
 * @LAYOUT_SIDERBAR_COLLAPSED_WIDTH  侧边导航栏收起宽度
 * @LAYOUT_SIDERBAR_ITEM_HEIGHT  侧边导航栏选项高度
 * @LAYOUT_SIDERBAR_CONTROL_HEIGHT  侧边导航栏控制按钮高度
 */
export const LAYOUT_HEADER_HEIGHT = '64px'
export const LAYOUT_SIDERBAR_WIDTH = '230px'
export const LAYOUT_SIDERBAR_COLLAPSED_WIDTH = '56px'
export const LAYOUT_SIDERBAR_ITEM_HEIGHT = '48px'
export const LAYOUT_SIDERBAR_CONTROL_HEIGHT = '48px'
